<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Accounting\Models\Currency;
use App\Modules\Accounting\Models\Tax;

class CurrencyAndTaxSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seed Currencies
        $currencies = [
            [
                'code' => 'USD',
                'name' => 'US Dollar',
                'symbol' => '$',
                'exchange_rate' => 1.000000,
                'is_base_currency' => true,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'before',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'EUR',
                'name' => 'Euro',
                'symbol' => '€',
                'exchange_rate' => 0.850000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'before',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'GBP',
                'name' => 'British Pound',
                'symbol' => '£',
                'exchange_rate' => 0.730000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'before',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'SAR',
                'name' => 'Saudi Riyal',
                'symbol' => 'ر.س',
                'exchange_rate' => 3.750000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'after',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'AED',
                'name' => 'UAE Dirham',
                'symbol' => 'د.إ',
                'exchange_rate' => 3.670000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'after',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'EGP',
                'name' => 'Egyptian Pound',
                'symbol' => 'ج.م',
                'exchange_rate' => 30.900000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'after',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'JPY',
                'name' => 'Japanese Yen',
                'symbol' => '¥',
                'exchange_rate' => 149.500000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 0,
                'symbol_position' => 'before',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'CAD',
                'name' => 'Canadian Dollar',
                'symbol' => 'C$',
                'exchange_rate' => 1.350000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'before',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'AUD',
                'name' => 'Australian Dollar',
                'symbol' => 'A$',
                'exchange_rate' => 1.520000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'before',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
            [
                'code' => 'CHF',
                'name' => 'Swiss Franc',
                'symbol' => 'CHF',
                'exchange_rate' => 0.880000,
                'is_base_currency' => false,
                'is_active' => true,
                'decimal_places' => 2,
                'symbol_position' => 'after',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
            ],
        ];

        foreach ($currencies as $currency) {
            Currency::updateOrCreate(
                ['code' => $currency['code']],
                $currency
            );
        }

        // Seed Taxes
        $taxes = [
            [
                'name' => 'VAT (Saudi Arabia)',
                'code' => 'VAT_SA',
                'rate' => 15.0000,
                'type' => 'vat',
                'description' => 'Value Added Tax for Saudi Arabia',
                'is_active' => true,
                'is_default' => true,
                'country_code' => 'SA',
                'region' => 'Middle East',
                'applies_to' => ['products', 'services'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '2018-01-01',
            ],
            [
                'name' => 'VAT (UAE)',
                'code' => 'VAT_AE',
                'rate' => 5.0000,
                'type' => 'vat',
                'description' => 'Value Added Tax for United Arab Emirates',
                'is_active' => true,
                'is_default' => false,
                'country_code' => 'AE',
                'region' => 'Middle East',
                'applies_to' => ['products', 'services'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '2018-01-01',
            ],
            [
                'name' => 'VAT (Egypt)',
                'code' => 'VAT_EG',
                'rate' => 14.0000,
                'type' => 'vat',
                'description' => 'Value Added Tax for Egypt',
                'is_active' => true,
                'is_default' => false,
                'country_code' => 'EG',
                'region' => 'Middle East',
                'applies_to' => ['products', 'services'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '2016-09-01',
            ],
            [
                'name' => 'Sales Tax (USA)',
                'code' => 'SALES_US',
                'rate' => 8.2500,
                'type' => 'sales_tax',
                'description' => 'Average Sales Tax for United States',
                'is_active' => true,
                'is_default' => false,
                'country_code' => 'US',
                'region' => 'North America',
                'applies_to' => ['products'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '2020-01-01',
            ],
            [
                'name' => 'VAT (UK)',
                'code' => 'VAT_GB',
                'rate' => 20.0000,
                'type' => 'vat',
                'description' => 'Value Added Tax for United Kingdom',
                'is_active' => true,
                'is_default' => false,
                'country_code' => 'GB',
                'region' => 'Europe',
                'applies_to' => ['products', 'services'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '2011-01-04',
            ],
            [
                'name' => 'GST (Canada)',
                'code' => 'GST_CA',
                'rate' => 5.0000,
                'type' => 'gst',
                'description' => 'Goods and Services Tax for Canada',
                'is_active' => true,
                'is_default' => false,
                'country_code' => 'CA',
                'region' => 'North America',
                'applies_to' => ['products', 'services'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '1991-01-01',
            ],
            [
                'name' => 'GST (Australia)',
                'code' => 'GST_AU',
                'rate' => 10.0000,
                'type' => 'gst',
                'description' => 'Goods and Services Tax for Australia',
                'is_active' => true,
                'is_default' => false,
                'country_code' => 'AU',
                'region' => 'Oceania',
                'applies_to' => ['products', 'services'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '2000-07-01',
            ],
            [
                'name' => 'VAT (EU Standard)',
                'code' => 'VAT_EU',
                'rate' => 21.0000,
                'type' => 'vat',
                'description' => 'Standard VAT rate for European Union',
                'is_active' => true,
                'is_default' => false,
                'country_code' => 'EU',
                'region' => 'Europe',
                'applies_to' => ['products', 'services'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '2006-01-01',
            ],
            [
                'name' => 'No Tax',
                'code' => 'NO_TAX',
                'rate' => 0.0000,
                'type' => 'other',
                'description' => 'No tax applied',
                'is_active' => true,
                'is_default' => false,
                'country_code' => null,
                'region' => null,
                'applies_to' => ['products', 'services', 'shipping'],
                'calculation_method' => 'percentage',
                'compound_tax' => false,
                'inclusive' => false,
                'effective_date' => '2020-01-01',
            ],
        ];

        foreach ($taxes as $tax) {
            Tax::updateOrCreate(
                ['code' => $tax['code']],
                $tax
            );
        }

        $this->command->info('Currencies and taxes seeded successfully!');
    }
}
