#!/bin/bash

echo "🚀 Creating Super Administrator Accounts for Connect Pure ERP"
echo "============================================================"

# Run the super admin seeder
echo "📦 Running Super Admin Seeder..."
php artisan db:seed --class=SuperAdminSeeder

echo ""
echo "🎉 Super Administrator Accounts Created!"
echo "========================================"
echo ""
echo "🔑 ADMIN ACCOUNTS CREATED:"
echo "========================="
echo ""
echo "1️⃣  MASTER ADMINISTRATOR"
echo "   📧 Email: master@connectpure.com"
echo "   🔐 Password: MasterAdmin@2024"
echo "   🛡️  Role: Master Admin (FULL ACCESS)"
echo ""
echo "2️⃣  SUPER ADMINISTRATOR"
echo "   📧 Email: superadmin@connectpure.com"
echo "   🔐 Password: SuperAdmin@2024"
echo "   🛡️  Role: Super Admin (FULL ACCESS)"
echo ""
echo "3️⃣  SYSTEM ADMINISTRATOR"
echo "   📧 Email: admin@connectpure.com"
echo "   🔐 Password: Admin@2024"
echo "   🛡️  Role: Master Admin + Top Management (FULL ACCESS)"
echo ""
echo "🌐 LOGIN URL: $(php artisan route:list | grep 'login' | head -1 | awk '{print $4}' || echo '/login')"
echo ""
echo "✅ PERMISSIONS GRANTED:"
echo "======================"
echo "• Full System Administration"
echo "• User & Role Management"
echo "• Complete HR Module Access"
echo "• Complete Accounting Module Access"
echo "• Complete CRM Module Access"
echo "• Complete Support Module Access"
echo "• Complete Performance Module Access"
echo "• Dashboard & Reports Access"
echo "• Settings & Configuration"
echo "• File Management"
echo "• API Access"
echo "• Audit & Logs"
echo "• Backup & Maintenance"
echo ""
echo "⚠️  SECURITY NOTICE:"
echo "==================="
echo "• Keep these credentials secure"
echo "• Change passwords after first login"
echo "• These accounts have UNRESTRICTED access"
echo "• Use for system administration only"
echo ""
echo "🎯 READY TO USE!"
echo "==============="
echo "Your Connect Pure ERP system now has full administrator accounts."
echo "Login with any of the above credentials to access all system functions."
